In [1]:
import numpy as np
import pandas as pd

### Numpy 
### Задание №1

In [9]:
a = np.array([[1, 6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание №2

In [14]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [25]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:, 1])
a_centered_sp

8.0

In [26]:
a_centered_sp = a_centered_sp / (a.shape[0] - 1)
a_centered_sp

2.0

### Задание 4

In [38]:
cov = np.cov(m = a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

In [39]:
cov[0,1]

2.0

### Pandas 
### Задание №1

In [28]:
authors = pd.DataFrame({'author_id' : [1, 2, 3],
                       'author_name' : ['Тургенев', 'Чехов', 'Островский']}, 
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [30]:
books = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                    'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                     'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price' : [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание №2

In [32]:
author_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание №3

In [33]:
top_5 = author_price.nlargest(5, 'price')
top_5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [34]:
min_author_price = author_price.groupby('author_name').agg({'price': 'min'})
min_author_price = min_author_price.reset_index()
min_author_price = min_author_price.rename(columns={'price':'min_price'})
min_author_price

author_name  min_price
0  Островский        290
1    Тургенев        300
2       Чехов        450

In [35]:
max_author_price = author_price.groupby('author_name').agg({'price': 'max'})
max_author_price = max_author_price.reset_index()
max_author_price = max_author_price.rename(columns={'price':'max_price'})
max_author_price

author_name  max_price
0  Островский        370
1    Тургенев        450
2       Чехов        500

In [36]:
mean_author_price = author_price.groupby('author_name').agg({'price': 'mean'})
mean_author_price = mean_author_price.reset_index()
mean_author_price = mean_author_price.rename(columns={'price':'mean_price'})
mean_author_price

author_name  mean_price
0  Островский  330.000000
1    Тургенев  366.666667
2       Чехов  475.000000

In [37]:
authors_stat_1 = pd.merge(min_author_price, max_author_price, on='author_name', how='inner')
authors_stat = pd.merge(authors_stat_1, mean_author_price, on='author_name', how='inner')
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

### Задание 5